### ISSUE TITLE
nl80211 issue with code structure concerning multiple waps

### ISSUE THREAD

**Issue by andrewhodel** [Alamot/alamot.github.io#1]
https://github.com/Alamot/alamot.github.io/blob/master/nl80211/index.html

You only get the stations for the first AP in your example, if you have multiple ap's running on a device you end up without some important information.

**Comment by Alamot** [comment]
Well, this example code is just a starting point, a tutorial. It is not meant to be thorough. One can easily modify/expand it to get info for all the APs et.c.
